In [1]:
#import libariry

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [24]:
#import dstaset
a= pd.read_csv("ford.csv")
print(a)

         model  year  price transmission  mileage fuelType  tax   mpg  \
0       Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7   
1        Focus  2018  14000       Manual     9083   Petrol  150  57.7   
2        Focus  2017  13000       Manual    12456   Petrol  150  57.7   
3       Fiesta  2019  17500       Manual    10460   Petrol  145  40.3   
4       Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7   
...        ...   ...    ...          ...      ...      ...  ...   ...   
17960   Fiesta  2016   7999       Manual    31348   Petrol  125  54.3   
17961    B-MAX  2017   8999       Manual    16700   Petrol  150  47.1   
17962    B-MAX  2014   7499       Manual    40700   Petrol   30  57.7   
17963    Focus  2015   9999       Manual     7010   Diesel   20  67.3   
17964       KA  2018   8299       Manual     5007   Petrol  145  57.7   

       engineSize  
0             1.0  
1             1.0  
2             1.0  
3             1.5  
4             1.0  
...

In [3]:
#check length of dataset
a.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [4]:
a.tail()

model  year  price transmission  mileage fuelType  tax   mpg  \
17960   Fiesta  2016   7999       Manual    31348   Petrol  125  54.3   
17961    B-MAX  2017   8999       Manual    16700   Petrol  150  47.1   
17962    B-MAX  2014   7499       Manual    40700   Petrol   30  57.7   
17963    Focus  2015   9999       Manual     7010   Diesel   20  67.3   
17964       KA  2018   8299       Manual     5007   Petrol  145  57.7   

       engineSize  
17960         1.2  
17961         1.4  
17962         1.0  
17963         1.6  
17964         1.2

In [5]:
#check datatypes of datasets
a.dtypes

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [6]:
#convert the value of tramission coloum data to (0,1,2)
a['transmission'].replace(['Automatic','Manual','Semi-Auto'],[0,1,2],inplace=True)
a.head()

model  year  price  transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000             0    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000             1     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000             1    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500             1    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500             0     1482   Petrol  145  48.7         1.0

In [7]:
#convert the value of tramission coloum data to (0,1,2)
a['fuelType'].replace(['Petrol','Diesel','Hybrid','Electric'],[0,1,2,3],inplace=True)
a

model  year  price  transmission  mileage  fuelType  tax   mpg  \
0       Fiesta  2017  12000             0    15944         0  150  57.7   
1        Focus  2018  14000             1     9083         0  150  57.7   
2        Focus  2017  13000             1    12456         0  150  57.7   
3       Fiesta  2019  17500             1    10460         0  145  40.3   
4       Fiesta  2019  16500             0     1482         0  145  48.7   
...        ...   ...    ...           ...      ...       ...  ...   ...   
17960   Fiesta  2016   7999             1    31348         0  125  54.3   
17961    B-MAX  2017   8999             1    16700         0  150  47.1   
17962    B-MAX  2014   7499             1    40700         0   30  57.7   
17963    Focus  2015   9999             1     7010         1   20  67.3   
17964       KA  2018   8299             1     5007         0  145  57.7   

       engineSize  
0             1.0  
1             1.0  
2             1.0  
3             1.5  
4             1.0  
...           ...  
17960         1.2  
17961         1.4  
17962         1.0  
17963         1.6  
17964         1.2  

[17965 rows x 9 columns]

In [8]:
#change the datatypes
c_dtypes = {'transmission': int,'fuelType': int }
a = a.astype(c_dtypes)
a.dtypes

model            object
year              int64
price             int64
transmission      int32
mileage           int64
fuelType          int32
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [9]:
#find the null values
pd.isnull(a).sum().sum()

0

In [10]:
#find duplicate rows
duplicate = a[a.duplicated()]
duplicate 

model  year  price  transmission  mileage  fuelType  \
159                     Focus  2016  10995             1    30923         1   
312                     Focus  2019  14998             1     7000         0   
349                     Focus  2019  14998             1     7000         0   
510                  EcoSport  2019  15489             1     5636         1   
512     Grand Tourneo Connect  2019  19999             1     3500         1   
...                       ...   ...    ...           ...      ...       ...   
14556                  Mondeo  2015   6793             1   138000         1   
15121                    Kuga  2017  14999             1    24877         1   
15127                EcoSport  2019  16799             0      433         0   
15685                      KA  2008   1795             1    63000         0   
17608                   B-MAX  2017  11495             0     5000         0   

       tax   mpg  engineSize  
159      0  74.3         1.5  
312    145  58.9         1.0  
349    145  58.9         1.0  
510    145  68.9         1.5  
512    145  61.4         1.5  
...    ...   ...         ...  
14556   20  68.9         2.0  
15121   30  64.2         1.5  
15127  150  45.6         1.0  
15685  160  45.6         1.3  
17608  145  44.1         1.6  

[154 rows x 9 columns]

In [11]:
# delete the null and duplicates values
b=a.dropna().drop_duplicates()
b

model  year  price  transmission  mileage  fuelType  tax   mpg  \
0       Fiesta  2017  12000             0    15944         0  150  57.7   
1        Focus  2018  14000             1     9083         0  150  57.7   
2        Focus  2017  13000             1    12456         0  150  57.7   
3       Fiesta  2019  17500             1    10460         0  145  40.3   
4       Fiesta  2019  16500             0     1482         0  145  48.7   
...        ...   ...    ...           ...      ...       ...  ...   ...   
17960   Fiesta  2016   7999             1    31348         0  125  54.3   
17961    B-MAX  2017   8999             1    16700         0  150  47.1   
17962    B-MAX  2014   7499             1    40700         0   30  57.7   
17963    Focus  2015   9999             1     7010         1   20  67.3   
17964       KA  2018   8299             1     5007         0  145  57.7   

       engineSize  
0             1.0  
1             1.0  
2             1.0  
3             1.5  
4             1.0  
...           ...  
17960         1.2  
17961         1.4  
17962         1.0  
17963         1.6  
17964         1.2  

[17811 rows x 9 columns]

In [12]:
b.dtypes


model            object
year              int64
price             int64
transmission      int32
mileage           int64
fuelType          int32
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [13]:
X = b.drop(['price','model'], axis=1)
y = b['price']

print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (17811, 7)
Shape of y =  (17811,)


In [14]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (14248, 7)
Shape of y_train =  (14248,)
Shape of X_test =  (3563, 7)
Shape of y_test =  (3563,)


In [15]:

sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [16]:

lr = LinearRegression()

lr.fit(X_train, y_train)

LinearRegression()

In [17]:
lr.coef_

array([ 2558.09620548,  -123.93593328, -1081.65826007,   754.37752637,
          42.94906626, -1209.60436854,  1690.06465797])

In [18]:
lr.intercept_

12263.459292532287

In [19]:
X_test[0, :]

array([ 0.07044656,  0.03628768,  1.41986186, -0.68250249,  0.18424996,
       -0.6430254 ,  0.3491125 ])

In [20]:
lr.predict([X_test[0, :]])

array([11764.24355233])

In [21]:
lr.predict(X_test)

array([11764.24355233, 14411.57032729,  7817.24815892, ...,
       10742.07005795,  9153.90797341, 14128.30073842])

In [22]:
y_test

15267    10300
2939     16311
5640      6690
14900     9000
11361    15999
         ...  
1511     13830
100       8998
10652    11995
2802      8990
14782    14299
Name: price, Length: 3563, dtype: int64

In [23]:
lr.score(X_test, y_test)

0.6904486605461586